import { Locale } from "./i18n";

const actionCopy = {
  zh: {
    common: {
      invalidAmount: "请输入合法的 USDT 金额，最多支持 6 位小数。",
      submitFailed: "提交失败，请稍后重试。",
      processingFailed: "处理失败，请稍后重试。",
      loginRequired: "请先登录后继续",
      noAdminAccess: "你没有后台权限",
    },
    auth: {
      validation: {
        displayNameMin: "显示名称至少 2 个字符",
        invalidEmail: "请输入正确的邮箱地址",
        passwordMin: "登录密码至少 8 位",
        confirmPasswordMismatch: "两次输入的密码不一致",
      },
      messages: {
        inviteCodeFailed: "邀请码生成失败，请稍后重试。",
        registerIncomplete: "注册信息不完整，请检查后重试。",
        emailRegistered: "该邮箱已注册，请直接登录。",
        inviteCodeMissing: "邀请码不存在，请确认后重试。",
        registerRetry: "注册失败，请重新提交。",
        registerSuccess: "注册成功，已自动登录。",
        signInIncomplete: "请填写完整的登录信息。",
        invalidCredentials: "账号或密码错误。",
        adminEntered: "已进入后台。",
        signInSuccess: "登录成功。",
        signedOut: "你已安全退出登录。",
      },
    },
    shop: {
      validation: {
        txHashInvalid: "请填写有效的交易哈希",
        txHashTooLong: "交易哈希长度异常",
      },
      messages: {
        rechargeIncomplete: "请填写完整的充值信息。",
        networkDisabled: (label: string) =>
          `${label} 当前尚未启用自动核验，请先使用已开启的网络充值。`,
        rechargeTooSmall: "单笔充值不得低于 10 USDT。",
        rechargeCreated: (serialNo: string) =>
          `充值单已创建，请按页面指引转账并提交交易哈希。订单号：${serialNo}`,
        proofIncomplete: "请填写完整的转账凭证。",
        rechargeMissing: "充值单不存在。",
        rechargeExpiredRecreate: "该充值单已过期，请重新创建。",
        rechargeProcessed: "该充值单已处理，不能重复提交。",
        txHashUsed: "该交易哈希已被其他充值单使用。",
        txHashSubmitted: "交易哈希已提交，系统开始自动核验链上状态。",
        recheckParamsInvalid: "核验参数错误。",
        rechargeUnauthorized: "你无权操作这笔充值单。",
        rechargeExpiredNoNeed: "该充值单已过期，无需再核验。",
        rechargeLocked: "当前充值单状态已锁定，不能再重新核验。",
        recheckSuccess: "已重新拉取链上状态。",
        orderIncomplete: "下单信息不完整。",
        productUnavailable: "该商品当前不可下单。",
        walletMissing: "钱包未初始化，请联系管理员。",
        balanceInsufficient: "平台余额不足，请先完成充值。",
        balanceChanged: "余额状态已变化，请刷新后重试。",
        orderSuccess: "下单成功，订单已进入人工处理队列。",
      },
    },
    admin: {
      validation: {
        productNameMin: "商品名称至少 2 个字符",
        productSubtitleMin: "副标题至少 4 个字符",
        productCategoryMin: "分类至少 2 个字符",
        productCoverRequired: "请填写封面简称",
        productSummaryMin: "简述至少 8 个字符",
        productDescriptionMin: "商品描述至少 16 个字符",
        productTagsRequired: "请填写标签",
        productDeliveryRequired: "请填写交付说明",
      },
      messages: {
        productIncomplete: "商品信息不完整。",
        productSaved: "商品已保存。",
        reviewParamsInvalid: "审核参数错误。",
        rechargeRejectChanged: "充值单状态已变化，无法重复驳回。",
        rechargeMissing: "充值单不存在。",
        rechargeExpiredNoCredit: "充值单已过期，不能再执行入账。",
        rechargeProcessed: "充值单已处理，不能重复入账。",
        rechargeTxHashRequired: "请先提交链上交易哈希，再执行审核。",
        userWalletMissing: "用户钱包不存在。",
        rechargeNotVerified: "链上核验尚未通过，不能直接入账。",
        rechargeCredited: "该充值单已经完成入账。",
        rechargeReviewed: "充值单已处理。",
        orderParamsInvalid: "订单状态参数错误。",
        orderMissingOrWallet: "订单不存在或用户钱包异常。",
        refundTransitionInvalid: "当前订单状态不允许直接切换为退款。",
        orderMissing: "订单不存在。",
        orderTransitionInvalid: "当前订单状态不允许这样流转。",
        orderUpdated: "订单状态已更新。",
      },
    },
  },
  en: {
    common: {
      invalidAmount: "Enter a valid USDT amount with up to 6 decimal places.",
      submitFailed: "Submission failed. Please try again later.",
      processingFailed: "Processing failed. Please try again later.",
      loginRequired: "Please sign in before continuing.",
      noAdminAccess: "You do not have admin access.",
    },
    auth: {
      validation: {
        displayNameMin: "Display name must be at least 2 characters.",
        invalidEmail: "Enter a valid email address.",
        passwordMin: "Password must be at least 8 characters.",
        confirmPasswordMismatch: "The two passwords do not match.",
      },
      messages: {
        inviteCodeFailed: "Failed to generate an invite code. Please try again.",
        registerIncomplete: "Registration details are incomplete.",
        emailRegistered: "This email is already registered. Please sign in.",
        inviteCodeMissing: "Invite code not found. Please check and try again.",
        registerRetry: "Registration failed. Please submit again.",
        registerSuccess: "Registration complete. You have been signed in.",
        signInIncomplete: "Please complete the sign-in form.",
        invalidCredentials: "Incorrect email or password.",
        adminEntered: "Admin access granted.",
        signInSuccess: "Signed in successfully.",
        signedOut: "You have been signed out safely.",
      },
    },
    shop: {
      validation: {
        txHashInvalid: "Enter a valid transaction hash.",
        txHashTooLong: "Transaction hash is too long.",
      },
      messages: {
        rechargeIncomplete: "Please complete the recharge form.",
        networkDisabled: (label: string) =>
          `${label} is not enabled for auto verification yet. Please use an enabled network.`,
        rechargeTooSmall: "A single recharge must be at least 10 USDT.",
        rechargeCreated: (serialNo: string) =>
          `Recharge order created. Please transfer funds and submit the transaction hash. Order: ${serialNo}`,
        proofIncomplete: "Please complete the transfer proof.",
        rechargeMissing: "Recharge order not found.",
        rechargeExpiredRecreate: "This recharge order expired. Please create a new one.",
        rechargeProcessed: "This recharge order has already been processed.",
        txHashUsed: "This transaction hash is already linked to another recharge order.",
        txHashSubmitted:
          "Transaction hash submitted. The system is now verifying the on-chain status.",
        recheckParamsInvalid: "Verification parameters are invalid.",
        rechargeUnauthorized: "You are not allowed to operate this recharge order.",
        rechargeExpiredNoNeed: "This recharge order has expired and no longer needs rechecking.",
        rechargeLocked: "This recharge order is locked and cannot be rechecked.",
        recheckSuccess: "On-chain status has been refreshed.",
        orderIncomplete: "Order details are incomplete.",
        productUnavailable: "This product is currently unavailable for ordering.",
        walletMissing: "Wallet is not initialized. Please contact support.",
        balanceInsufficient: "Insufficient platform balance. Please recharge first.",
        balanceChanged: "Balance changed. Please refresh and try again.",
        orderSuccess: "Order placed successfully and added to the manual queue.",
      },
    },
    admin: {
      validation: {
        productNameMin: "Product name must be at least 2 characters.",
        productSubtitleMin: "Subtitle must be at least 4 characters.",
        productCategoryMin: "Category must be at least 2 characters.",
        productCoverRequired: "Please enter a cover abbreviation.",
        productSummaryMin: "Summary must be at least 8 characters.",
        productDescriptionMin: "Description must be at least 16 characters.",
        productTagsRequired: "Please enter tags.",
        productDeliveryRequired: "Please enter a delivery note.",
      },
      messages: {
        productIncomplete: "Product details are incomplete.",
        productSaved: "Product saved.",
        reviewParamsInvalid: "Review parameters are invalid.",
        rechargeRejectChanged: "Recharge status changed and can no longer be rejected again.",
        rechargeMissing: "Recharge order not found.",
        rechargeExpiredNoCredit: "Recharge order expired and can no longer be credited.",
        rechargeProcessed: "Recharge order has already been processed.",
        rechargeTxHashRequired: "Submit the transaction hash before approving the recharge.",
        userWalletMissing: "User wallet not found.",
        rechargeNotVerified: "On-chain verification has not passed yet.",
        rechargeCredited: "This recharge order has already been credited.",
        rechargeReviewed: "Recharge order updated.",
        orderParamsInvalid: "Order status parameters are invalid.",
        orderMissingOrWallet: "Order not found or user wallet is unavailable.",
        refundTransitionInvalid: "This order cannot be switched directly to refunded.",
        orderMissing: "Order not found.",
        orderTransitionInvalid: "This order cannot transition to that status.",
        orderUpdated: "Order status updated.",
      },
    },
  },
  ko: {
    common: {
      invalidAmount: "USDT 금액을 올바르게 입력하세요. 소수점은 최대 6자리까지 지원합니다.",
      submitFailed: "제출에 실패했습니다. 잠시 후 다시 시도하세요.",
      processingFailed: "처리에 실패했습니다. 잠시 후 다시 시도하세요.",
      loginRequired: "계속하려면 먼저 로그인하세요.",
      noAdminAccess: "관리자 권한이 없습니다.",
    },
    auth: {
      validation: {
        displayNameMin: "표시 이름은 2자 이상이어야 합니다.",
        invalidEmail: "올바른 이메일 주소를 입력하세요.",
        passwordMin: "비밀번호는 8자 이상이어야 합니다.",
        confirmPasswordMismatch: "두 비밀번호가 일치하지 않습니다.",
      },
      messages: {
        inviteCodeFailed: "초대 코드 생성에 실패했습니다. 잠시 후 다시 시도하세요.",
        registerIncomplete: "회원가입 정보가 완전하지 않습니다.",
        emailRegistered: "이미 등록된 이메일입니다. 바로 로그인하세요.",
        inviteCodeMissing: "초대 코드를 찾을 수 없습니다. 다시 확인하세요.",
        registerRetry: "회원가입에 실패했습니다. 다시 제출하세요.",
        registerSuccess: "회원가입이 완료되었고 자동으로 로그인되었습니다.",
        signInIncomplete: "로그인 정보를 모두 입력하세요.",
        invalidCredentials: "이메일 또는 비밀번호가 올바르지 않습니다.",
        adminEntered: "관리자 화면으로 이동했습니다.",
        signInSuccess: "로그인되었습니다.",
        signedOut: "안전하게 로그아웃되었습니다.",
      },
    },
    shop: {
      validation: {
        txHashInvalid: "유효한 거래 해시를 입력하세요.",
        txHashTooLong: "거래 해시 길이가 너무 깁니다.",
      },
      messages: {
        rechargeIncomplete: "충전 정보를 모두 입력하세요.",
        networkDisabled: (label: string) =>
          `${label} 네트워크는 아직 자동 검증이 활성화되지 않았습니다. 활성화된 네트워크를 사용하세요.`,
        rechargeTooSmall: "1회 충전 금액은 최소 10 USDT여야 합니다.",
        rechargeCreated: (serialNo: string) =>
          `충전 주문이 생성되었습니다. 안내에 따라 송금 후 거래 해시를 제출하세요. 주문번호: ${serialNo}`,
        proofIncomplete: "송금 증빙 정보를 모두 입력하세요.",
        rechargeMissing: "충전 주문을 찾을 수 없습니다.",
        rechargeExpiredRecreate: "이 충전 주문은 만료되었습니다. 새로 생성하세요.",
        rechargeProcessed: "이 충전 주문은 이미 처리되었습니다.",
        txHashUsed: "이 거래 해시는 다른 충전 주문에서 이미 사용 중입니다.",
        txHashSubmitted: "거래 해시가 제출되었고 온체인 상태 검증이 시작되었습니다.",
        recheckParamsInvalid: "검증 파라미터가 올바르지 않습니다.",
        rechargeUnauthorized: "이 충전 주문을 처리할 권한이 없습니다.",
        rechargeExpiredNoNeed: "이 충전 주문은 만료되어 다시 검증할 필요가 없습니다.",
        rechargeLocked: "현재 충전 주문 상태가 잠겨 있어 다시 검증할 수 없습니다.",
        recheckSuccess: "온체인 상태를 다시 가져왔습니다.",
        orderIncomplete: "주문 정보가 완전하지 않습니다.",
        productUnavailable: "이 상품은 현재 주문할 수 없습니다.",
        walletMissing: "지갑이 초기화되지 않았습니다. 관리자에게 문의하세요.",
        balanceInsufficient: "플랫폼 잔액이 부족합니다. 먼저 충전하세요.",
        balanceChanged: "잔액 상태가 변경되었습니다. 새로고침 후 다시 시도하세요.",
        orderSuccess: "주문이 접수되어 수동 처리 대기열에 추가되었습니다.",
      },
    },
    admin: {
      validation: {
        productNameMin: "상품명은 2자 이상이어야 합니다.",
        productSubtitleMin: "부제목은 4자 이상이어야 합니다.",
        productCategoryMin: "분류는 2자 이상이어야 합니다.",
        productCoverRequired: "커버 약칭을 입력하세요.",
        productSummaryMin: "요약은 8자 이상이어야 합니다.",
        productDescriptionMin: "상품 설명은 16자 이상이어야 합니다.",
        productTagsRequired: "태그를 입력하세요.",
        productDeliveryRequired: "전달 설명을 입력하세요.",
      },
      messages: {
        productIncomplete: "상품 정보가 완전하지 않습니다.",
        productSaved: "상품이 저장되었습니다.",
        reviewParamsInvalid: "검토 파라미터가 올바르지 않습니다.",
        rechargeRejectChanged: "충전 상태가 변경되어 다시 거절할 수 없습니다.",
        rechargeMissing: "충전 주문을 찾을 수 없습니다.",
        rechargeExpiredNoCredit: "충전 주문이 만료되어 입금 처리할 수 없습니다.",
        rechargeProcessed: "이 충전 주문은 이미 처리되었습니다.",
        rechargeTxHashRequired: "승인 전에 거래 해시를 먼저 제출해야 합니다.",
        userWalletMissing: "사용자 지갑을 찾을 수 없습니다.",
        rechargeNotVerified: "온체인 검증이 아직 통과되지 않았습니다.",
        rechargeCredited: "이 충전 주문은 이미 입금 처리되었습니다.",
        rechargeReviewed: "충전 주문이 처리되었습니다.",
        orderParamsInvalid: "주문 상태 파라미터가 올바르지 않습니다.",
        orderMissingOrWallet: "주문을 찾을 수 없거나 사용자 지갑이 비정상입니다.",
        refundTransitionInvalid: "현재 주문 상태에서는 바로 환불로 전환할 수 없습니다.",
        orderMissing: "주문을 찾을 수 없습니다.",
        orderTransitionInvalid: "현재 주문 상태에서는 해당 흐름 전환이 허용되지 않습니다.",
        orderUpdated: "주문 상태가 업데이트되었습니다.",
      },
    },
  },
} as const;

export function getActionCopy(locale: Locale) {
  return actionCopy[locale];
}
